import './style.css';
import {el,button,field,area,select,uid,request} from './dom.js';
import {parseProtocol,sampleProtocol,type Protocol,type Page,type Question,type Group,type AssetInfo,type Condition} from '../shared/protocol.js';
const app=document.querySelector<HTMLDivElement>('#app')!,message=document.querySelector<HTMLParagraphElement>('#message')!;
let csrf='',role='';
const api=<T>(url:string,data?:unknown)=>request<T>(url,data,csrf);
async function action(fn:()=>Promise<void>){try{message.textContent='正在处理…';await fn();message.textContent='';}catch(error){message.textContent=error instanceof Error?error.message:'操作失败';}}
function login(){app.replaceChildren();const section=el('section');section.append(el('h2','登录'));const password=field('密码','','password'),r=select('角色',[{value:'researcher',label:'研究者'},{value:'maintainer',label:'维护者'}],'researcher');password.input.autocomplete='current-password';
section.append(r.box,password.box,button('登录',()=>action(async()=>{const result=await api<{csrf:string;role:string}>('/api/auth/login',{password:password.input.value,role:r.input.value});csrf=result.csrf;role=result.role;await list();})),el('p','首次使用：在服务器执行 npm run auth:setup 配置研究者密码；维护者使用 npm run auth:setup -- maintainer。','muted'));app.append(section);}
function nav(){const bar=el('nav');bar.append(button('研究列表',()=>action(list)),button('维护作业',()=>action(jobs)),button('运行状态',()=>action(async()=>{const state=await api('/api/lab/operations');app.replaceChildren(nav(),el('h2','运行状态'),el('pre',JSON.stringify(state,null,2)));})),button('环境准入',()=>action(environments)),button('退出',()=>action(async()=>{await api('/api/auth/logout',{});login();})));return bar;}
interface Study {study_id:string;title:string;revision:number;admission:string;version_id:string|null}
async function list(){const {studies}=await api<{studies:Study[]}>('/api/lab/studies');app.replaceChildren(nav());const top=el('div',undefined,'toolbar');top.append(el('h2','研究'),button('新建研究',()=>action(async()=>{const s=await api<{study_id:string}>('/api/lab/studies',{request_id:uid()});await edit(s.study_id);})));app.append(top);
if(!studies.length)app.append(el('section','尚无研究。新建后可编辑问卷、上传图片并发布测试版本。'));
for(const s of studies){const card=el('section');card.append(el('h2',s.title),el('p',`草稿修订 ${s.revision} · 接入${s.admission==='OPEN'?'开放':'暂停'}`));const controls=el('div',undefined,'toolbar');controls.append(button('编辑与发布',()=>action(()=>edit(s.study_id))),button('数据与质量',()=>action(()=>sessions(s.study_id))),button(s.admission==='OPEN'?'暂停新接入':'开放新接入',()=>action(async()=>{await api(`/api/lab/studies/${s.study_id}/admission`,{request_id:uid(),paused:s.admission==='OPEN'});await list();})));
if(s.version_id){const a=el('a','参与链接');a.href=`/participate.html?version=${s.version_id}`;a.target='_blank';a.rel='noopener';controls.append(a);}card.append(controls);app.append(card);}}
interface StudyDraft extends Study {draft:Protocol;versions:{version_id:string;hash:string;created_at:number}[]}
async function edit(study:string){const s=await api<StudyDraft>(`/api/lab/studies/${study}`);let p=structuredClone(s.draft);let assets=(await api<{assets:AssetInfo[]}>(`/api/lab/studies/${study}/assets`)).assets;
let dirty=false;const change=()=>{dirty=true;};const redraw=()=>render();
function conditionEditor(target:{condition?:Condition},label:string){const panel=el('details');panel.append(el('summary',label));const json=area('条件 AST（空白表示始终显示）',target.condition?JSON.stringify(target.condition,null,2):'',3);json.input.addEventListener('change',()=>{try{if(json.input.value.trim())target.condition=JSON.parse(json.input.value) as Condition;else delete target.condition;change();}catch{message.textContent='条件格式错误。支持 eq/neq/includes/and/or/not，引用必须来自前序问题。';}});panel.append(json.box,el('p','例：{"op":"eq","question":"ready","value":"是"}。条件不执行脚本。','muted'));return panel;}
function questionCard(page:Page,q:Question){const card=el('div',undefined,'editor-card');const title=field('题目',q.title),type=select('题型',[{value:'single',label:'单选'},{value:'multi',label:'多选'},{value:'scale',label:'量表'},{value:'text',label:'短文本'}],q.type);
title.input.oninput=()=>{q.title=title.input.value;change();};type.input.onchange=()=>{q.type=type.input.value as Question['type'];delete q.choices;delete q.min;delete q.max;delete q.max_length;if(q.type==='single'||q.type==='multi')q.choices=['选项一','选项二'];if(q.type==='scale'){q.min=1;q.max=5;}if(q.type==='text')q.max_length=200;change();redraw();};const required=field('必答','','checkbox');required.input.checked=q.required;required.input.onchange=()=>{q.required=required.input.checked;change();};
card.append(title.box,type.box,required.box);if(q.choices){const choices=area('选项（每行一个）',q.choices.join('\n'));choices.input.onchange=()=>{q.choices=choices.input.value.split('\n').filter(v=>v.trim());change();};card.append(choices.box);}
for(const key of q.type==='scale'?['min','max'] as const:q.type==='text'?['max_length'] as const:[]){const f=field(key==='min'?'最小分值':key==='max'?'最大分值':'最多字符',String(q[key]),'number');f.input.onchange=()=>{q[key]=Number(f.input.value);change();};card.append(f.box);}
card.append(conditionEditor(q,'题目显示条件'),button('删除题目',()=>{page.questions=page.questions.filter(v=>v!==q);change();redraw();},'secondary'));return card;}
function render(){app.replaceChildren(nav());const title=field('研究名称',p.title);title.input.oninput=()=>{p.title=title.input.value;change();};const mode=select('采集标签',[{value:'TEST_ONLY',label:'测试数据'},{value:'COLLECTION',label:'正式采集（需维护者准入）'}],p.mode);mode.input.onchange=()=>{p.mode=mode.input.value as Protocol['mode'];change();};const controls=el('div',undefined,'toolbar');
controls.append(button('保存草稿',()=>action(async()=>{const result=await api<{revision:number;draft:Protocol}>(`/api/lab/studies/${study}/save`,{request_id:uid(),revision:s.revision,protocol:parseProtocol(p)});s.revision=result.revision;p=result.draft;dirty=false;message.textContent='草稿已保存。';})),button('冻结并发布',()=>action(async()=>{if(dirty){const result=await api<{revision:number}>(`/api/lab/studies/${study}/save`,{request_id:uid(),revision:s.revision,protocol:parseProtocol(p)});s.revision=result.revision;dirty=false;}const version=await api<{version_id:string}>(`/api/lab/studies/${study}/publish`,{request_id:uid(),revision:s.revision});const card=el('section');const a=el('a','打开已发布版本');a.href=`/participate.html?version=${version.version_id}`;a.target='_blank';card.append(el('h2','版本已冻结'),a,el('p','参与前还需在研究列表开放新接入。后续草稿修改会生成新版本。'));app.prepend(card);})));app.append(el('h2','编辑研究'),title.box,mode.box,controls);
const resource=el('section');resource.append(el('h2','图片资源'));const upload=field('上传静态 PNG/JPEG/WebP','','file');upload.input.accept='image/png,image/jpeg,image/webp';upload.input.multiple=true;upload.input.onchange=()=>void action(async()=>{for(const file of Array.from(upload.input.files??[])){const response=await fetch(`/api/lab/studies/${study}/upload`,{method:'POST',headers:{'Content-Type':file.type,'X-CSRF-Token':csrf,'X-Request-Id':uid(),'X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json() as {code?:string};if(!response.ok)throw new Error(result.code??'UPLOAD_FAILED');}assets=(await api<{assets:AssetInfo[]}>(`/api/lab/studies/${study}/assets`)).assets;redraw();});resource.append(upload.box);
for(const a of assets){const row=el('div',undefined,'asset-row');row.append(el('span',`${a.name} · ${a.state}${a.width?` · ${a.width}×${a.height}`:''}`));if(a.state==='READY'){const image=el('img');image.src=`/api/lab/assets/${a.asset_id}`;image.alt=a.name;row.prepend(image);}if(role==='maintainer'&&['READY','FAILED','DELETING'].includes(a.state))row.append(button('维护删除',()=>action(async()=>{await api(`/api/lab/assets/${a.asset_id}/delete`,{request_id:uid()});await edit(study);}),'secondary'));resource.append(row);}app.append(resource);
const pages=el('section');pages.append(el('h2','问卷与说明页'));for(const page of p.pages){const card=el('article');const title=field('页面标题',page.title),instruction=area('说明文字',page.instruction);title.input.oninput=()=>{page.title=title.input.value;change();};instruction.input.oninput=()=>{page.instruction=instruction.input.value;change();};card.append(title.box,instruction.box,conditionEditor(page,'页面分支条件'));for(const q of page.questions)card.append(questionCard(page,q));card.append(button('添加题目',()=>{page.questions.push({id:`q-${uid()}`,type:'single',title:'新题目',required:true,choices:['选项一','选项二']});change();redraw();}),button('删除页面',()=>{p.pages=p.pages.filter(v=>v!==page);change();redraw();},'secondary'));pages.append(card);}pages.append(button('添加页面',()=>{p.pages.push({id:`p-${uid()}`,title:'新页面',instruction:'',questions:[]});change();redraw();}));app.append(pages);
const groups=el('section');groups.append(el('h2','图片选择任务'));for(const g of p.groups){const card=el('article');const title=field('组名称',g.title),choices=area('响应按钮（每行一个）',g.choices.join('\n'));title.input.oninput=()=>{g.title=title.input.value;change();};choices.input.onchange=()=>{g.choices=choices.input.value.split('\n').filter(v=>v.trim());change();};const repeats=select('异常补测上限',[{value:'0',label:'关闭补测'},{value:'1',label:'最多追加 1 次'},{value:'2',label:'最多追加 2 次（默认）'}],String(g.repeats));repeats.input.onchange=()=>{g.repeats=Number(repeats.input.value);change();};card.append(title.box,choices.box,repeats.box);
for(const t of g.trials){const row=el('div',undefined,'trial-row');const asset=select('图片',assets.filter(a=>a.state==='READY').map(a=>({value:a.asset_id,label:a.name})),t.asset_id);asset.input.onchange=()=>{t.asset_id=asset.input.value;change();};row.append(asset.box);for(const key of ['image_ms','isi_ms'] as const){const f=field(key==='image_ms'?'图片时长 ms':'空屏时长 ms',String(t[key]),'number');f.input.onchange=()=>{t[key]=Number(f.input.value);change();};row.append(f.box);}const correct=select('正确答案',[{value:'',label:'未设置'},...g.choices.map(c=>({value:c,label:c}))],t.correct??'');correct.input.onchange=()=>{t.correct=correct.input.value||null;change();};row.append(correct.box,button('移除',()=>{g.trials=g.trials.filter(v=>v!==t);change();syncVariants();redraw();},'secondary'));card.append(row);}
card.append(el('p',`原始 ${g.trials.length} 次；最坏 ${g.trials.length*(g.repeats+1)} 次；最长 ${Math.round(g.trials.reduce((n,t)=>n+(t.image_ms+t.isi_ms)*(g.repeats+1),0)/1000)} 秒。`),button('添加试次',()=>{const a=assets.find(a=>a.state==='READY');if(!a){message.textContent='请先上传一张通过检查的图片。';return;}g.trials.push({root_id:`t-${uid()}`,asset_id:a.asset_id,image_ms:1000,isi_ms:300,correct:null});change();syncVariants();redraw();}),button('删除图片组',()=>{p.groups=p.groups.filter(v=>v!==g);change();syncVariants();redraw();},'secondary'));groups.append(card);}groups.append(button('添加图片组',()=>{p.groups.push({id:`g-${uid()}`,title:'新图片组',choices:['左','右'],repeats:2,trials:[]});change();syncVariants();redraw();}));app.append(groups);
const advanced=el('details',undefined,'advanced');advanced.append(el('summary','方案、布局、预算与完整协议'));const json=area('协议 JSON（应用后进行共享合同校验）',JSON.stringify(p,null,2),20);advanced.append(json.box,button('应用协议配置',()=>{try{p=parseProtocol(JSON.parse(json.input.value));change();redraw();}catch(error){message.textContent=error instanceof Error?error.message:'协议无效';}}),el('p','分组模式用多个组；全任务连续模式用一个组。方案表定义各组及根的完整顺序和权重。TEST_ONLY 的时序/资源预算需要真实设备验收后才能用于正式版本。','muted'));app.append(advanced);
const versions=el('section');versions.append(el('h2','已冻结版本'));for(const v of s.versions){const a=el('a',`${new Date(v.created_at).toLocaleString()} · ${v.hash.slice(0,12)}`);a.href=`/participate.html?version=${v.version_id}`;a.target='_blank';const row=el('p');row.append(a);versions.append(row);}app.append(versions);
}
function syncVariants(){for(const v of p.variants){const groups=p.groups.map(g=>g.id);v.group_order=[...v.group_order.filter(id=>groups.includes(id)),...groups.filter(id=>!v.group_order.includes(id))];v.trial_order=Object.fromEntries(p.groups.map(g=>{const roots=g.trials.map(t=>t.root_id),old=v.trial_order[g.id]??[];return [g.id,[...old.filter(id=>roots.includes(id)),...roots.filter(id=>!old.includes(id))]];}));}}
render();}
async function sessions(study:string){const result=await api<{sessions:{session_id:string;state:string;page_index:number;group_index:number;diagnostics:number;last_received:number|null}[]}>(`/api/lab/studies/${study}/sessions`);app.replaceChildren(nav());const top=el('div',undefined,'toolbar');top.append(el('h2','会话与数据质量'),button('导出全状态 CSV',()=>action(async()=>{const result=await api<{job_id:string}>('/api/lab/jobs/export',{request_id:uid(),job_id:uid(),study_id:study});const a=el('a','下载 CSV');a.href=`/api/lab/jobs/${result.job_id}/data.csv`;app.prepend(a);})));if(role==='maintainer')top.append(button('重建派生结果（先暂停接入并关闭运行）',()=>action(async()=>{await api('/api/lab/jobs/rebuild',{request_id:uid(),job_id:uid(),study_id:study});message.textContent='新派生代已发布。';})));app.append(top);
for(const s of result.sessions){const card=el('section');card.append(el('h3',s.session_id),el('p',`${s.state} · 已确认页面位置 ${s.page_index} · 组位置 ${s.group_index} · ${s.diagnostics} 项诊断`),el('p',s.last_received?`最后接收：${new Date(s.last_received).toLocaleString()}`:'尚无事件；不能推断参加者实时状态。'),button('详情与问题标记',()=>action(async()=>{
const detail=await api<Record<string,unknown>>(`/api/lab/sessions/${s.session_id}`);const container=el('section');container.append(el('h2','核查详情'));const pre=el('pre',JSON.stringify(detail,null,2));container.append(pre);const note=area('核查备注','');container.append(note.box,button('追加问题标记',()=>action(async()=>{await api(`/api/lab/sessions/${s.session_id}/marks`,{request_id:uid(),mark_id:uid(),revision:1,type:'REVIEW',note:note.input.value,status:'OPEN'});container.append(el('p','问题标记已保存；原始答案和系统诊断保持独立。'));})));app.append(container);
})));app.append(card);}}
async function jobs(){const result=await api<{jobs:{job_id:string;kind:string;state:string;phase:string;error:string|null}[]}>('/api/lab/jobs');app.replaceChildren(nav(),el('h2','维护作业'));if(role==='maintainer')app.append(button('生成联合备份',()=>action(async()=>{await api('/api/lab/jobs/backup',{request_id:uid(),job_id:uid()});await jobs();})));for(const job of result.jobs){const card=el('section');card.append(el('h3',`${job.kind} · ${job.state}`),el('p',`${job.job_id} · ${job.phase}`));if(job.error)card.append(el('p',job.error));if(job.state==='READY'&&['EXPORT','BACKUP'].includes(job.kind)){const a=el('a','下载清单');a.href=`/api/lab/jobs/${job.job_id}/manifest.json`;card.append(a);}if(job.state==='RECOVERY_REQUIRED'&&role==='maintainer'){const report=area('故障核查报告','');card.append(report.box,button('核验文件并结束失败作业',()=>action(async()=>{await api(`/api/lab/jobs/${job.job_id}/recover`,{request_id:uid(),report:report.input.value});await jobs();})));}app.append(card);}}
async function environments(){app.replaceChildren(nav(),el('h2','正式采集准入'));const records=await api<{environments:unknown[]}>('/api/lab/environments');app.append(el('pre',JSON.stringify(records.environments,null,2)));if(role!=='maintainer'){app.append(el('p','环境验收和准入恢复由维护者执行。'));return;}const name=field('环境标识',''),record=area('环境验收档案 JSON',JSON.stringify({hardware:'',filesystem:'',device_matrix:'',capacity_report:'',independent_restore_report:'',backup_target:'',backup_job_id:'',restore_manifest_hash:'',restore_verified:false,rpo:'',rto:'',operator:'',verified_at:''},null,2),14);app.append(name.box,record.box,button('登记环境档案',()=>action(async()=>{await api('/api/lab/environments',{request_id:uid(),environment_id:name.input.value,record:JSON.parse(record.input.value)});await environments();})),button('关闭正式新接入',()=>action(async()=>{await api('/api/lab/collection-gate/close',{request_id:uid()});})),button('按已登记环境开放正式采集',()=>action(async()=>{await api('/api/lab/collection-gate',{request_id:uid(),environment_id:name.input.value});message.textContent='正式采集准入已记录。';})),el('p','登记内容必须指向真实设备、容量和独立恢复证据。开发夹具不证明正式环境可用。'));}
void action(async()=>{try{const me=await api<{csrf:string;role:string}>('/api/auth/me');csrf=me.csrf;role=me.role;await list();}catch{login();}});
