import type {InteractionBatch,InteractionContext,InteractionSample,InteractionScreen,ScreenNode} from '../shared/interaction.js';
// Separate diagnostic chains preserve every browser-delivered/coalesced drag sample
// without changing answer seals or the experiment scheduler's replay protocol.
export function recordInteractions(root:HTMLElement,context:()=>InteractionContext,save:(batch:InteractionBatch)=>Promise<unknown>,fail:(error:unknown)=>void){
  let samples:InteractionBatch['samples']=[],timer:ReturnType<typeof setTimeout>|undefined,closed=false,pending=Promise.resolve();const listeners:[EventTarget,string,EventListener][]=[];let onset=performance.now(),position='',lastScreen='',bytes=0;
  const box=(e:Element)=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};};
  const flush=()=>{clearTimeout(timer);timer=undefined;if(!samples.length)return pending;const batch={schema:'interaction-v1' as const,time_origin:performance.timeOrigin,samples};samples=[];bytes=0;pending=save(batch).then(()=>{}).catch(fail);return pending;};
  const add=(sample:InteractionBatch['samples'][number])=>{if(closed)return;const size=new TextEncoder().encode(JSON.stringify(sample)).length;if(bytes+size>90000)void flush();samples.push(sample);bytes+=size;if(samples.length>=64)void flush();else timer??=setTimeout(()=>{void flush();},100);};
  const identify=(node:Element)=>{if(node.id)return `#${node.id}`;const path:string[]=[];let e:Element|null=node;while(e&&e!==root){path.unshift(`${e.tagName.toLowerCase()}:nth-child(${Array.from(e.parentElement?.children??[]).indexOf(e)+1})`);e=e.parentElement;}return path.join('>');};
  const styles=['color','background-color','border-top-width','border-top-style','border-top-color','border-radius','font-family','font-size','font-weight','line-height','text-align','padding','opacity','white-space'] as const;
  function screen(){if(closed)return;const c=context(),key=JSON.stringify([c.page_id,c.question_id,c.instance_id,c.item,c.phase]);if(key!==position){position=key;onset=performance.now();}const nodes:ScreenNode[]=[];for(const e of root.querySelectorAll<HTMLElement>('*')){const r=box(e),c=getComputedStyle(e);if(!r.width||!r.height||c.visibility!=='visible'||c.display==='none'||e.closest('[style*="opacity: 0"]'))continue;const style=Object.fromEntries(styles.map(k=>[k,c.getPropertyValue(k)]));const node:ScreenNode={...r,tag:e.tagName.toLowerCase(),text:'',style};if(e instanceof HTMLInputElement){node.value=e.value;node.tag=e.type==='range'?'range':'input';node.disabled=e.disabled;node.checked=e.checked;if(e.type==='range'){node.style.min=e.min;node.style.max=e.max;node.style.answered=e.dataset.answered??'false';}}if(e instanceof HTMLButtonElement)node.disabled=e.disabled;if(e instanceof HTMLCanvasElement){node.asset_id=context().asset_id;node.text=context().stimulus_text??'';}nodes.push(node);for(const child of e.childNodes)if(child.nodeType===Node.TEXT_NODE&&child.textContent?.trim()){const range=document.createRange();range.selectNodeContents(child);const rect=range.getBoundingClientRect();nodes.push({x:rect.x,y:rect.y,width:rect.width,height:rect.height,tag:'text',text:child.textContent,style});}if(nodes.length>1900)break;}
    const signature=JSON.stringify([context(),innerWidth,innerHeight,scrollX,scrollY,nodes]);if(signature===lastScreen)return;lastScreen=signature;const v=visualViewport;add({type:'screen',at:performance.now(),context:context(),width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scroll_x:scrollX,scroll_y:scrollY,visual_viewport:v?{x:v.offsetLeft,y:v.offsetTop,width:v.width,height:v.height,scale:v.scale}:null,background:getComputedStyle(document.documentElement).backgroundColor,nodes});}
  function event(e:Event){const target=e.target instanceof Element?e.target:root;const pointer=e instanceof PointerEvent;const list=pointer&&e.type==='pointermove'?(e.getCoalescedEvents?.().length?e.getCoalescedEvents():[e]):[e];for(const item of list){const p=item instanceof PointerEvent?item:null,k=item instanceof KeyboardEvent?item:null;const sample:InteractionSample={type:e.type,at:item.timeStamp<=performance.now()+1?item.timeStamp:item.timeStamp-performance.timeOrigin,raw_timestamp:item.timeStamp,context:context(),target:identify(target),box:box(target),x:p?.clientX??null,y:p?.clientY??null,trusted:e.isTrusted,...(p?{pointer_id:p.pointerId,pointer_type:p.pointerType,button:p.button,buttons:p.buttons,pressure:p.pressure}:{}),...(k?{key:k.key,code:k.code}:{}),...(target instanceof HTMLInputElement?{value:target.value}:{}),...(e instanceof InputEvent?{input_type:e.inputType}:{})};sample.rt_ms=Math.max(0,sample.at-onset);add(sample);}if(!['pointermove','pointerrawupdate'].includes(e.type))queueMicrotask(screen);}
  const listen=(target:EventTarget,type:string,handler:EventListener)=>{target.addEventListener(type,handler,{capture:true,passive:true});listeners.push([target,type,handler]);};
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel','click','keydown','keyup','input','change','focusin','focusout','compositionstart','compositionend'])listen(root,type,event);
  listen(window,'resize',screen);listen(window,'scroll',screen);listen(document,'visibilitychange',screen);screen();
  return {screen,flush,stop:()=>{closed=true;for(const [target,type,handler]of listeners)target.removeEventListener(type,handler,true);void flush();}};
}
