import {taskLiveness} from './task-liveness.js';
import {recordInteractions} from './interaction-recorder.js';
import {el,button} from './dom.js';
import {RunReplay} from '../shared/run-replay.js';
import type {GroupPlan,RunRecord} from '../shared/lab-contract.js';
import type {ParticipantAPI} from './participant-api.js';
export function ratingControls(prompts:string[],labels:string[],buttons:HTMLButtonElement[],footer:HTMLElement,agePrompt?:string){
  const controls=el('div',undefined,'rating-controls'),heading=el('p',prompts[0]);heading.id='rating-prompt';
  const axes=prompts.map((prompt,index)=>{const axis=el('div',undefined,'rating-axis axis-control');axis.style.visibility='hidden';const ends=el('div',undefined,'axis-ends');ends.append(el('span',`1 · ${labels[0] ?? ''}`),el('span',`${labels.length} · ${labels.at(-1) ?? ''}`));const track=el('div',undefined,'axis-track'),range=el('input',undefined,'axis-input');range.type='range';range.min='1';range.max=String(labels.length);range.step='1';range.value='5';range.dataset.answered='false';range.setAttribute('aria-label',prompt);const ticks=el('div',undefined,'rating-ticks');ticks.setAttribute('aria-hidden','true');for(let i=0;i<labels.length;i++)ticks.append(el('span',String(i+1)));track.append(range);const bottom=el('div',undefined,'axis-bottom'),output=el('output','点击或拖动坐标轴选择评分');bottom.append(output);axis.append(ends,track,ticks,bottom);return {axis,range};});
  controls.style.visibility='hidden';controls.append(heading,...axes.map(a=>a.axis));
  const age=agePrompt?document.createElement('input'):null;if(age){const row=el('div',undefined,'rating-age-row');row.style.visibility='hidden';age.type='text';age.readOnly=true;age.inputMode='none';age.pattern='[0-9]{1,3}';age.placeholder='点击下方数字输入年龄';age.setAttribute('aria-label',agePrompt!);age.className='rating-age';
    const keypad=el('div',undefined,'rating-age-keypad');keypad.setAttribute('role','group');keypad.setAttribute('aria-label','年龄数字键盘');
    const enter=(key:string)=>{const value=key==='Backspace'?age.value.slice(0,-1):age.value.length<3?age.value+key:age.value;if(value===age.value)return;age.value=value;age.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:key==='Backspace'?'deleteContentBackward':'insertText',data:key==='Backspace'?null:key}));};
    for(const digit of ['1','2','3','4','5','6','7','8','9','0'])keypad.append(button(digit,()=>enter(digit)));
    keypad.append(button('退格',()=>enter('Backspace')));age.onkeydown=event=>{if(/^[0-9]$/.test(event.key)||event.key==='Backspace'){event.preventDefault();enter(event.key);}};row.append(age,keypad);controls.append(row);}
  const submit=el('button',prompts.length>1?'下一题':'提交评分');submit.type='button';submit.hidden=false;submit.style.visibility='hidden';submit.disabled=true;footer.append(submit);return {controls,submit,heading,prompts,age,ranges:axes.map(a=>a.range),axes:axes.map(a=>a.axis)};
}
export async function runRating(plan:GroupPlan,a:ParticipantAPI,canvas:HTMLCanvasElement,buttons:HTMLButtonElement[],ranges:HTMLInputElement[],axes:HTMLElement[],submit:HTMLButtonElement,heading:HTMLElement,age:HTMLInputElement|null,images:Map<string,ImageBitmap>,ctx:CanvasRenderingContext2D,status:HTMLElement,geometry:()=>NonNullable<GroupPlan['geometry']>,release:()=>void,returnToPage:()=>void,content:HTMLElement){
  const replay=new RunReplay(plan),origin=performance.now(),now=()=>performance.now()-origin;const items=plan.rating?.items?.length??1;const total=items+(age?1:0);let question=0,index=0,phase:'waiting'|'rating'|'isi'|'closing'='waiting',intentReady=false,selected:number|null=null,answers:number[]=[];let submission:{values:number[];at:number}|null=null,frame=0,lastFrame=0,stopped=false,clearAt=0,answerSaved=false;
  const instance=()=>`${plan.roots[index]!.root_id}:1`,persist=(r:RunRecord)=>a.ledger.append(plan.scope,'GROUP_RECORD',{record:r}),emit=(r:RunRecord)=>{r.clock_origin=origin;replay.apply(r);return persist(r)};const blank=()=>{ctx.fillStyle=a.session.frozen.protocol.layout.background;ctx.fillRect(0,0,canvas.width,canvas.height);canvas.style.visibility='hidden';};const visible=(show:boolean)=>{const c=axes[0]?.parentElement;if(c){c.style.visibility=show?'visible':'hidden';c.style.opacity=show?'1':'0';c.style.pointerEvents=show?'auto':'none';}submit.style.visibility=show?'visible':'hidden';};const disable=()=>{for(const b of buttons)b.disabled=true;for(const r of ranges)r.disabled=true;submit.disabled=true;};
  const recorder=recordInteractions(document.querySelector('main')!,()=>({instance_id:instance(),item:question,phase,asset_id:plan.roots[index]?.asset_id}),batch=>a.ledger.interaction(batch),error=>{void stop(error);});
  const resetQuestion=(q:number)=>{for(const [i,r] of ranges.entries()){r.disabled=i!==q;r.dataset.answered='false';r.value='5';const out=r.closest('.axis-control')?.querySelector('output');if(out)out.textContent='点击或拖动坐标轴选择评分';r.closest('.axis-control')?.querySelectorAll('.rating-ticks span').forEach(t=>(t as HTMLElement).dataset.selected='false');}axes.forEach((axis,i)=>axis.style.visibility=i===q?'visible':'hidden');};
  const stopLiveness=taskLiveness(a,reason=>{void stop(reason);});
  async function intent(){intentReady=false;await emit({type:'RATING_INTENT',at:now(),instance_id:instance()});if(!stopped)intentReady=true;}function remove(){stopLiveness();recorder.stop();document.body.classList.remove('running');window.removeEventListener('resize',change);document.removeEventListener('visibilitychange',change);window.removeEventListener('pagehide',hidden);window.visualViewport?.removeEventListener('resize',visualChange);window.visualViewport?.removeEventListener('scroll',visualChange);}async function stop(error:unknown){if(stopped)return;stopped=true;cancelAnimationFrame(frame);blank();disable();remove();await persist({type:'ABORT',at:now(),clock_origin:origin,reason:String(error).slice(0,150)}).catch(()=>{});status.textContent=String(error)==='USER_IDLE_TIMEOUT'?'连续2分钟未操作，任务已中断，正在保存已有评分。':'任务已中断，正在保存已有评分。';await a.terminate('SOFTWARE_RUN_INTERRUPTED',{reason:String(error).slice(0,150)}).catch(()=>{});await a.sync().catch(()=>{});release();document.body.classList.remove('runner-layout');content.replaceChildren(button('返回核对保存记录',returnToPage));}
  const typing=()=>phase==='rating'&&question===items&&document.activeElement===age;const change=()=>{if(typing()&&document.visibilityState==='visible')return;if(document.visibilityState!=='visible'||JSON.stringify(geometry())!==JSON.stringify(plan.geometry))void stop('VISIBILITY_OR_GEOMETRY_CHANGED');};const visualChange=()=>{if(!typing())void stop('VISUAL_VIEWPORT_CHANGED');},hidden=()=>void stop('PAGE_HIDDEN_OR_CLOSED');window.addEventListener('resize',change);document.addEventListener('visibilitychange',change);window.addEventListener('pagehide',hidden);window.visualViewport?.addEventListener('resize',visualChange);window.visualViewport?.addEventListener('scroll',visualChange);
  const choose=(value:number)=>{if(phase!=='rating'||submission||stopped)return;selected=value;const range=ranges[question]!;range.dataset.answered='true';range.setAttribute('aria-valuetext',`${value}：${plan.rating!.labels[value-1] ?? ""}`);range.closest('.axis-control')?.querySelectorAll('.rating-ticks span').forEach((t,i)=>(t as HTMLElement).dataset.selected=String(i===value-1));const output=range.closest('.axis-control')?.querySelector('output');if(output)output.textContent=`已选 ${value}：${plan.rating!.labels[value-1] ?? ""}`;void emit({type:'RATING_CHANGE',at:now(),instance_id:instance(),item:question,value}).catch(stop);submit.disabled=false;status.textContent=`第 ${index+1}/${plan.roots.length} 张 · ${plan.rating!.items?.[question]??plan.rating!.prompt} · 已选 ${value}：${plan.rating!.labels[value-1] ?? ""}`;};if(age)age.oninput=()=>{submit.disabled=question!==items||!/^\d{1,3}$/.test(age.value)||Number(age.value)>120;};for(const range of ranges){let pointer:number|null=null;
    const update=(x:number)=>{const rect=range.getBoundingClientRect(),value=1+Math.round(Math.max(0,Math.min(1,(x-rect.left-11)/Math.max(1,rect.width-22)))*(plan.choices.length-1));if(range.dataset.answered!=='true'||Number(range.value)!==value){range.value=String(value);choose(value);}};
    range.onpointerdown=event=>{if(phase!=='rating'||range.disabled||event.button!==0)return;event.preventDefault();pointer=event.pointerId;range.setPointerCapture(pointer);update(event.clientX);};
    range.onpointermove=event=>{if(pointer===event.pointerId&&!range.disabled){event.preventDefault();update(event.clientX);}};
    range.onpointerup=event=>{if(pointer===event.pointerId){update(event.clientX);if(range.hasPointerCapture(pointer))range.releasePointerCapture(pointer);pointer=null;}};
    range.onpointercancel=()=>{pointer=null;};range.onlostpointercapture=()=>{pointer=null;};
    range.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();choose(Number(range.value));}};range.oninput=()=>choose(Number(range.value));range.onchange=()=>choose(Number(range.value));}

  submit.onclick=()=>{if(phase!=='rating'||submission||stopped)return;if(question===items){const value=Number(age?.value);if(!age?.value.trim()||!Number.isInteger(value)||value<0||value>120){status.textContent='请输入 0–120 之间的整数年龄';return;}answers[question]=value;}else{if(selected===null)return;answers[question]=selected;}if(question<total-1){question++;selected=null;resetQuestion(question);if(age)age.parentElement!.style.visibility=question===items?'visible':'hidden';submit.disabled=true;heading.textContent=question===items?(plan.rating!.age_prompt??'年龄'):plan.rating!.items?.[question]??plan.rating!.prompt;submit.textContent=question===total-1?'提交评分':'下一题';status.textContent=`第 ${index+1}/${plan.roots.length} 张 · ${heading.textContent}`;recorder.screen();return;}submission={values:[...answers],at:now()};disable();};
  async function finish(){phase='closing';disable();remove();try{await emit({type:'CLOSING',at:now(),unresolved:false});replay.finish();await a.ledger.drain();await a.ledger.closeScope(plan.scope,[...a.session.path,plan.group_id]);status.textContent='评分已完成，正在保存与核对…';await a.seal(plan.scope);await a.sync();release();returnToPage();}catch(error){if((await a.ledger.state()).pending[plan.scope]){release();document.body.classList.remove('runner-layout');status.textContent='评分已完成，保存与封存待重试。';content.replaceChildren(button('重试保存与核对',async()=>{try{await a.seal(plan.scope);await a.sync();returnToPage();}catch(e){status.textContent=String(e);}}));}else await stop(error);}}
  function tick(raf:number){if(stopped||phase==='closing')return;const at=now();try{if(lastFrame&&at-lastFrame>plan.budget.long_frame_ms)throw new Error('LONG_FRAME');lastFrame=at;if(phase==='waiting'&&intentReady&&at>=plan.start){const root=plan.roots[index]!,image=images.get(root.asset_id!)!;if(!image)throw new Error('RATING_IMAGE_NOT_PREPARED');ctx.fillStyle=a.session.frozen.protocol.layout.background;ctx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/image.width,canvas.height/image.height),w=image.width*scale,h=image.height*scale;ctx.drawImage(image,(canvas.width-w)/2,(canvas.height-h)/2,w,h);canvas.style.visibility='visible';void emit({type:'ONSET',at,draw_time:now(),raf_time:raf-origin,instance_id:instance()}).catch(stop);phase='rating';visible(true);question=0;answers=[];selected=null;submission=null;if(age){age.parentElement!.style.visibility='hidden';age.value='';}resetQuestion(0);submit.disabled=true;submit.textContent=items>1?'下一题':'提交评分';heading.textContent=plan.rating!.items?.[0]??plan.rating!.prompt;status.textContent=`第 ${index+1}/${plan.roots.length} 张 · ${heading.textContent}`;recorder.screen();}else if(phase==='rating'&&submission){blank();visible(false);clearAt=now();const answer=submission;phase='isi';answerSaved=false;disable();status.textContent='评分已记录，请等待下一张。';recorder.screen();void emit({type:'RATING',at,draw_time:clearAt,raf_time:raf-origin,input_time:answer.at,instance_id:instance(),values:answer.values}).then(()=>{answerSaved=true;}).catch(stop);}else if(phase==='isi'&&answerSaved&&at>=clearAt+plan.roots[index]!.isi_ms){void emit({type:'END',at,instance_id:instance()}).catch(stop);index++;if(index===plan.roots.length){void finish();return;}phase='waiting';void intent().catch(stop);}}catch(error){void stop(error);return;}frame=requestAnimationFrame(tick);}
  document.body.classList.add('running');submit.style.visibility='hidden';disable();blank();visible(false);await intent();if(!stopped)frame=requestAnimationFrame(tick);
}
